#!/bin/bash
#**********************************************************************************************************************
#**********************************************************************************************************************
#									DHSM_2.0_CREDENTIAL_AGANT_INIT_SCRIPT
#**********************************************************************************************************************
#**********************************************************************************************************************

#======================================================================================================================
#CONSTANT/VARIABLE
#=====================================================================================================================

#FILE_CONSTANT
readonly UTIL_SCRIPT="__PREFIX__/bin/credential-agent/common_utils"
readonly AGENT_CONF_FILE="__PREFIX__/etc/credential_agent.ini"
readonly AGENT_COMMANDLINE_TOOL="__PREFIX__/bin/credential_agent_tool"


#VARIABLE
declare CRED_SERVICE_IP=""
declare TOKEN=""
declare CA_CERT_PATH=""

##=====================================================================================================================
##COMMON_UTILS
##=====================================================================================================================
if [ -f $UTIL_SCRIPT ]; then
	source $UTIL_SCRIPT
	set_log $FLAG_ENABLE
	log_msg $LOG_DEBUG "Utils included"
else
	echo "$UTIL_SCRIPT inclusion"
	exit -1
fi
#=====================================================================================================================

source $AGENT_CONF_FILE


check_credential_agent_installed()
{
	if [ ! -f $AGENT_COMMANDLINE_TOOL ]; then	
		exit_script $LOG_ERROR "Credential Agent Tool not installed" $CODE_INSTALL_ERROR
	fi
}

issue_cert()
{
	local issue_cert_cmd="$AGENT_COMMANDLINE_TOOL --get-certificate --verbose --force --config $AGENT_CONF_FILE"
	$(check_last_cmd_exec_status "$issue_cert_cmd" $EXEC_RULE_ABORT "ISSUE_CERT_FROM_CRED_INIT" $CODE_EXEC_ERROR)
}

renew_cert_job()
{

	local is_cert_abt_to_exp="openssl x509 -checkend ${cert_validity} -noout -in $certificate"
	$(check_last_cmd_exec_status "$is_cert_abt_to_exp" $EXEC_RULE_ABORT "Certificate Validatity" $CODE_OPENSSL_ERROR)
	local renew_cert_cmd="unset http_proxy && unset https_proxy && $AGENT_COMMANDLINE_TOOL --renew-certificate --verbose --config $AGENT_CONF_FILE"
	local renew_cron_job="$renew_job_interval $renew_cert_cmd"
	#log_msg $LOG_DEBUG "RENEW JOB:$renew_cron_job"
	crontab -l | grep "renew-certificate" 
	if [[ $? -ne 0 ]]; then
		#log_msg $LOG_DEBUG "$renew_cron_job"
		local renew_cron_job_tmp=$(mktemp)
		crontab -l > $renew_cron_job_tmp
		echo "$renew_cron_job" >> $renew_cron_job_tmp
		crontab $renew_cron_job_tmp
		if [[ $? -ne 0 ]]; then  
			rm $renew_cron_job_tmp
		   exit_script $LOG_ERROR "Crontab job" $CODE_INSTALL_ERROR	
		fi
		rm $renew_cron_job_tmp
	else
		log_msg $LOG_WARN "Renew Certificate job already schedule and crontab"
	fi
	crontab -l
}

usage()
{
	log_msg $LOG_WARN "$0 <CRENDIAL_SERVICE_[IP/HOSTNAME]> <CSR_TOKEN> <CA_CERT>"	
	exit_script $LOG_WARN "Invalid commandline args" $CODE_PARSE_ERROR
}

main()
{
	check_credential_agent_installed
	issue_cert
	renew_cert_job
}

trap 'send_status' 1 2 3 6

main







