#!/bin/bash
readonly UTIL_SCRIPT="__PREFIX__/bin/credential-agent/common_utils"
readonly AGENT_CONF_FILE="__PREFIX__/etc/credential_agent.ini"
readonly AGENT_COMMANDLINE_TOOL="__PREFIX__/bin/credential_agent_tool"

if [ -f $UTIL_SCRIPT ]; then
	source $UTIL_SCRIPT
	set_log $FLAG_ENABLE
	log_msg $LOG_DEBUG "Utils included"
else
	echo "$UTIL_SCRIPT inclusion"
	exit -1
fi

source $AGENT_CONF_FILE

issue_cert()
{
	local issue_cert_cmd="$AGENT_COMMANDLINE_TOOL --get-certificate --verbose --force --config $AGENT_CONF_FILE"
	$(check_last_cmd_exec_status "$issue_cert_cmd" $EXEC_RULE_ABORT "ISSUE_CERT_FROM_CRED_INIT" $CODE_EXEC_ERROR)
}

add_intermediate_ca() {
	local intermediate_path=/opt/skc/store/inter.pem
	`curl -X GET -v "https://$server:$port/cms/v1/ca-certificates?issuingCa=TLS-Client"\
	-H 'Accept: application/x-pem-file' --cacert $ca_cert> $intermediate_path`

	local line=$(tail -n 1 $intermediate_path)
	if [[ $line != "-----END CERTIFICATE-----" ]]; then
		echo "issue: intermediate certificate not added to CA certificate. please add manually."
		return
	else
		cat $intermediate_path $ca_cert >>$ca_cert
	fi
	rm -rf $intermediate_path
}

issue_cert
add_intermediate_ca
